version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: make ci:diff
      - run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make || exit 255"
  release:
    machine: true
    steps:
      - checkout
      - run:
          name: Install awscli
          command: pip install awscli
      - run:
          name: Install jq
          command: sudo apt-get update && sudo apt-get install jq
      - run:
          name: Install github-release
          command: go get -u github.com/aktau/github-release
      - run:
          name: Build
          command: |
            cd `echo "$CIRCLE_TAG" | cut -d'/' -f 1` && make
      - run:
          name: Release to AWS
          command: |
            cd `echo "$CIRCLE_TAG" | cut -d'/' -f 1` && make release
      - run:
          name: Release to GitHub
          command: |
            github-release upload -u cw-ozaki -r lambda-layers -t "$CIRCLE_TAG" -n ${name:=`echo "$CIRCLE_TAG" | cut -d'/' -f 1`}.zip -f ${name}/${name}.zip

workflows:
  version: 2
  integration:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              # e.g. shell-runtime/0.0.0
              only: /^.*\/.*$/
            branches:
              ignore: /.*/
